[project]
name = "mkcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "face-recognition>=1.3.0",
    "fastapi>=0.116.1",
    "opencv-python>=4.12.0.88",
]
